`ucr` Expanded service option setting

diff --git a/ucr b/ucr
--- a/ucr
+++ b/ucr
@@ -43,6 +43,41 @@ ucr_api_url_pattern="^https?://[\.A-Za-z0-9:-]+"
 ucr_dis_url_pattern="^https?://[\.A-Za-z0-9:-]+"
 ucr_biz_url_pattern="^https?://[\.A-Za-z0-9:-]+"
 
+# Internal function to fetch service schema and cache it
+# Check cache for service operations, if missing or older than a week, fetch new.
+# If --no-cache, always fetch new.
+function fetch_service_schema {
+  want_envs UCR_API_URL "$ucr_api_url_pattern" UCR_SID "^[a-zA-Z0-9]+$"
+  local service=${1:?Need service name}
+
+  local cache_file="${XDG_CACHE_HOME:-$HOME/.cache}/ucr/${service}-schema.json"
+  mkdir -p ${cache_file:h}
+  # If it doesn't exist, cache is false
+  [[ -f $cache_file ]] || ucr_opts[cache]=false
+  # If it exists, then check the age (this will set ucr_opts[cache] to false if too old)
+  [[ -f $cache_file && -z "${cache_file}(N,md-7)" ]] && ucr_opts[cache]=false
+  if [[ ${ucr_opts[cache]} == "false" ]]; then
+    local ecf=$(mktemp -t sc-cache.ecf.XXXXXX)
+    v_curl -s ${UCR_API_URL}/service/${(L)service}/schema \
+      --write-out "%output{>>${ecf}}%{exitcode},%{http_code},%{errormsg}" \
+      -o $cache_file
+      local ec http_code errormsg
+      IFS=',' read -r ec http_code errormsg < $ecf
+      if [[ $ec != "0" || $http_code != "200" ]]; then
+        echo "Error fetching schema for service $service: $http_code $errormsg" >&2
+        rm -f $cache_file
+        rm -f $ecf
+        exit 2
+      fi
+      rm -f $ecf
+  fi
+  # Cache_file is a JSON formatted OpenAPI v2 schema for the service
+  # v3 isn't supported by Murano yet.
+  # Assumptions are made
+
+  echo "$cache_file"
+}
+
 ##############################################################################
 # Define the tasks for this tool
 
@@ -227,7 +262,7 @@ ucr solution create SID=<solution id> [BID=<business id>] [<options>] domain
   Key-Values:
     SID       Solution Identifier (required)
     BID       Business Identifier (optional)
-  Options:  
+  Options:
     --m2                Create an M2 Connector type solution instead of application
     --exchange=<ids>    Comma separated list of exchange ids to apply
 
@@ -330,6 +365,116 @@ function ucr_service_details {
   v_curl -s ${UCR_API_URL}/serviceconfig/${UCR_SID}_${(L)service}
 }
 
+function ucr_help_service_set {
+  cat <<EOF
+ucr service set <service> [--listparams] [--no-cache] [--in=FILE] [options]
+  Set the configuration for a service in a solution.
+
+  Use --listparams to list the parameters for the operation.
+  Use --no-cache to force fetching the operations from the API. (still updates cache)
+  Use --in=FILE to read parameters from a JSON file in addition to command line options.
+  If FILE is '-', read from STDIN.
+
+  --noMergeParam=true|false
+    If true, parameters not specified are removed from the service config.
+    If false (default), parameters not specified are left unchanged.
+  --noParamOverload=<list>|true
+    Comma separated list of parameters that should not be overloaded.
+    If 'true', all parameters are protected from overload.
+
+  Options are mapped to parameters by name, and validated against the parameter pattern if provided.
+  All parameters are passed as options, none are positional.
+  If both options and --in are given, the options override any values in the file.
+
+EOF
+}
+function ucr_service_set {
+  want_envs UCR_API_URL "$ucr_api_url_pattern" UCR_SID "^[a-zA-Z0-9]+$"
+  local service=${1:?Need service name}
+
+  local query_opts=$(
+    options_to_json \
+    noMergeParam::boolean "^(true|1|yes|ok|y|t|false|no|n|f)$" \
+    noParamOverload::string "^([a-zA-Z0-9_-]+(,[a-zA-Z0-9_-]+)*)$|^true$"
+  )
+  [[ -n "$query_opts" ]] && query_opts="?$(jq -r 'to_entries|map("\(.key)=\(.value)")|join("&")' <<< $query_opts)"
+
+  # Fetch schema for service.
+  local cache_file
+  cache_file=$(fetch_service_schema "$service") || exit $?
+  # Extract 'x-exosite-config-parameters' and follow refs to build a parameter list with patterns.
+  local operation_parameters=$(jq 'def deref($d):
+    if type == "object" and has("$ref") then
+      ((.["$ref"] | split("/") | .[1:]) as $p | $d | getpath($p)) + {"name": .name}
+    else
+      .
+    end;
+    . as $doc
+    | .["x-exosite-config-parameters"]
+    | walk(deref($doc)) | walk(deref($doc))' $cache_file)
+  [[ -z "${ucr_opts[debug]}" ]] || echo "Service parameters: $operation_parameters" >&2
+
+  local opt_req='{}'
+  if [[ $(jq 'length' <<< $operation_parameters) > 0 ]]; then
+    local param_patterns=($(jq -r '.[] |
+    	.type |= if (.|type) == "array" then
+        "object"
+      else
+        .
+      end |
+      .rex = if (.|has("pattern")) then
+        .pattern
+      elif (.| has("enum")) then
+        "^(" + (.enum|join("|")) + ")$"
+      elif .type == "string" then
+        "^.*$"
+      elif .type == "integer" then
+        "^[0-9]+$"
+      elif .type == "number" then
+        "^[0-9]+(\\.[0-9]+)?$"
+      elif .type == "boolean" then
+        "^(true|1|yes|ok|y|t|false|no|n|f)$"
+      else
+        "^.*$"
+      end |
+      "\(if (. | has("x-exosite-from")) then .["x-exosite-from"] else .name end)::\(.type)", "\(.rex)"' <<< $operation_parameters))
+    # echo "= = $param_patterns" >&2
+    [[ -n "$param_patterns" ]] && opt_req=$( options_to_json "${(@)param_patterns}")
+    [[ -z "$opt_req" ]] && exit 4
+  fi
+
+  # --listparams will just list the parameters for the operation
+  if [[ -n "$ucr_opts[listparams]" ]]; then
+    if [[ $(jq 'length' <<< $operation_parameters) > 0 ]]; then
+      for (( i=1; i<=$#param_patterns; i+=2 )); do
+        local key=${param_patterns[i]%%::*}
+        local type=${param_patterns[i]#*::}
+        local rex=${param_patterns[i+1]}
+        echo " --$key=<${type} by $rex>"
+      done
+      return
+    else
+      echo "No parameters for service $service" >&2
+      return
+    fi
+  fi
+
+  if [[ -n "${ucr_opts[in]}" ]]; then
+    local file=${ucr_opts[in]}
+    # If --in is `-`, use STDIN
+    [[ "$file" == "-" ]] && file=/dev/stdin
+    # Merge with opt_req
+    opt_req=$(jq --argjson opt "$opt_req" '. * $opt' $file)
+  fi
+
+  [[ -z "${ucr_opts[debug]}" ]] || echo "Req: $opt_req" >&2
+
+  v_curl -s ${UCR_API_URL}/serviceconfig/${UCR_SID}_${(L)service}${query_opts} \
+    -H 'Content-Type: application/json' \
+    -X PUT \
+    -d "$opt_req"
+}
+
 function ucr_help_service_add {
   cat <<EOF
 ucr service add <service>
@@ -362,7 +507,7 @@ function ucr_service_delete {
 }
 
 ####################
-# Service 
+# Service
 
 function ucr_help_service_schema {
   cat <<EOF
@@ -432,7 +577,7 @@ function ucr_service_install {
 }
 
 function ucr_help_service_uninstall {
-  cat <<EOF 
+  cat <<EOF
 ucr service uninstall <service>
   Uninstall a service
 EOF
@@ -459,13 +604,6 @@ function ucr_service_get {
 }
 
 ####################
-
-function ucr_help_template_update {
-  ucr_help_solution_update
-}
-function ucr_template_update {
-  ucr_solution_update "$@"
-}
 
 function ucr_help_solution_update {
   cat <<EOF
@@ -561,7 +699,7 @@ function ucr_business_token {
 function ucr_help_business_solutions {
   cat <<EOF
 ucr business solutions
-  List all solutions for the business 
+  List all solutions for the business
 EOF
 }
 function ucr_business_solutions {
@@ -629,27 +767,8 @@ function ucr_sc {
 
   # Check cache for service operations, if missing or older than a week, fetch new.
   # If --no-cache, always fetch new.
-  local cache_file="${XDG_CACHE_HOME:-$HOME/.cache}/ucr/${service}-schema.json"
-  mkdir -p ${cache_file:h}
-  # If it doesn't exist, cache is false
-  [[ -f $cache_file ]] || ucr_opts[cache]=false
-  # If it exists, then check the age (this will set ucr_opts[cache] to false if too old)
-  [[ -f $cache_file && -z "${cache_file}(N,md-7)" ]] && ucr_opts[cache]=false
-  if [[ ${ucr_opts[cache]} == "false" ]]; then
-    local ecf=$(mktemp -t sc-cache.ecf.XXXXXX)
-    v_curl -s ${UCR_API_URL}/service/${(L)service}/schema \
-      --write-out "%output{>>${ecf}}%{exitcode},%{http_code},%{errormsg}" \
-      -o $cache_file
-      local ec http_code errormsg
-      IFS=',' read -r ec http_code errormsg < $ecf
-      if [[ $ec != "0" || $http_code != "200" ]]; then
-        echo "Error fetching schema for service $service: $http_code $errormsg" >&2
-        rm -f $cache_file
-        rm -f $ecf
-        exit 2
-      fi
-      rm -f $ecf
-  fi
+  local cache_file
+  cache_file=$(fetch_service_schema "$service") || exit $?
   # Cache_file is a JSON formatted OpenAPI v2 schema for the service
   # v3 isn't supported by Murano yet.
   # Assumptions are made
@@ -789,10 +908,10 @@ function _dis_call {
 
   local ecf=$(mktemp -t discall.ecf.XXXXXX)
 
-  local res=$(v_curl -s ${UCR_DIS_URL}/call/${UCR_SID}/${(L)service}/${operation}\?noWrap\=true \
+  local res=$(v_curl -s ${UCR_DIS_URL}/call/${UCR_SID}/${(L)service}/${operation} \
     --write-out "%output{>>${ecf}}%{http_code},%{content_type}" \
     -H 'Content-Type: application/json' \
-    -d "$data" 
+    -d "$data"
   )
 
   local ec content_type
@@ -851,11 +970,11 @@ if [[ -z "${ucr_opts[short]}" ]]; then
                                Defaults to RFC3339 UTC.
     --mode=(merge|split)       Merge all metrics into a single time series, or split into multiple
                                series by tag combinations. Default is merge.
-    --fill=(null|previous|none|<number>|~s:.+) 
+    --fill=(null|previous|none|<number>|~s:.+)
                                Fill missing data points with null, previous value, no fill, a
                                specific number, or a string.  Only in mode=merge.
     --order_by=(desc|asc)      Order results by timestamp descending or ascending. Default is desc.
-    --aggregate=(avg|min|max|count|sum),+ 
+    --aggregate=(avg|min|max|count|sum),+
                                Aggregate data points using the specified functions.
                                Can specify multiple functions separated by commas.
                                Note: aggregate requires sampling_size to be set.
@@ -927,7 +1046,7 @@ function ucr_tsdb_exports {
   )
   [[ -z "$opt_req" ]] && exit 4
 
-  _dis_call tsdb exportJobList "$opt_req" 
+  _dis_call tsdb exportJobList "$opt_req"
 }
 
 function ucr_help_tsdb_export_info {
@@ -974,23 +1093,23 @@ if [[ -z "${ucr_opts[short]}" ]]; then
 
   Formatting:
     ORDER MATTERS! FE: round before label is different than label before round
-    
+
     <metric>#label#<string>
     3456789#label#foo
       Prefix value with 'foo'
-    
+
     <metric>#round#<number>
     3456789#round#9
       Round by 9
-    
+
     <metric>#rename#<string>
     34567890#rename#bob
       Replace metric name with 'bob'
-    
+
     <metric>#replace#<regexp>#<replace>
     123456#replace#([0-9])([0-9])#\2-\1
       Do regexp on value. replace uses '\1' for capture groups.
-    
+
     <metric>|timestamp#datetime#<date format>#<offset>
     98765#datetime#year_%Y#-4
       Apply a datetime format to the value. Value should be microseconds since the EPOCH.
@@ -1031,7 +1150,7 @@ function ucr_tsdb_export {
   #  mode "(merge|split)"
   # Illegal query options: (passing them returns error)
   #  sampling_size "[1-9][0-9]*(u|ms|s|m|h|d|w)?"
-  #  aggregate "((avg|min|max|count|sum),?)+" 
+  #  aggregate "((avg|min|max|count|sum),?)+"
   local opt_req=$(
     options_to_json \
     start_time "[1-9][0-9]*(u|ms|s)?" \
@@ -1227,7 +1346,7 @@ function ucr_content_list {
   want_envs UCR_API_URL "$ucr_api_url_pattern" UCR_SID "^[a-zA-Z0-9]+$"
   # list [--op=AND|OR] [--stop=#] [<prefix filter>] [<tag name filter>@<tag value filter> ...]
   local opt_req=$(options_to_json \
-    op "^(AND|OR)$" 
+    op "^(AND|OR)$"
   )
   [[ -z "$opt_req" ]] && exit 4
 
